channels:
- conda-forge
dependencies:
- python=3.12.6
- pip<=25.1.1
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.1
  - numpy==2.1.3
  - pandas==2.3.0
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.15.2
name: mlflow-env
